# Clase 3
## Ejercicio 1

In [2]:
import numpy as np
import pandas as pd
rng = np.random.default_rng(seed=18)

In [8]:
data = pd.read_csv("clase3.csv",delimiter=';',header=None)
data

0         1         2         3         4          5          6
0   -7.365651 -2.200942  0.826385  1.805224       NaN  -1.455761        NaN
1   -1.802595  2.540484       NaN -1.371999  0.559279  -6.215952        NaN
2   -4.768005  0.083384  6.958399  0.618383  1.881193  -4.126731 -29.548485
3    0.207910  4.657893  5.261442  0.092837 -6.822636   2.160200  -1.252347
4    5.109047  3.617160  0.720485  4.707807  2.589978   4.882425  45.406797
..        ...       ...       ...       ...       ...        ...        ...
95  14.019013 -0.915209  0.693633 -1.054584  0.851131  20.618052  54.929472
96  13.392036  0.836150       NaN  1.758533 -3.497701 -17.576979        NaN
97   0.816928 -2.372775  3.859463  0.965103 -7.095862   1.302221  -0.094008
98   5.226607  1.044207  4.330368  0.819687  0.839239   2.576468  14.570347
99   9.511769  0.059136  4.847053 -0.840450 -2.079400   8.087163  23.201129

[100 rows x 7 columns]

In [10]:
#referencia de resultados con pandas
data.describe()

0           1          2           3          4           5  \
count  100.000000  100.000000  75.000000  100.000000  85.000000  100.000000   
mean     1.824495    1.344289   4.428483    0.807150  -0.787840   -1.944483   
std      8.616492    2.379364   4.349173    1.419509   3.100910    6.637331   
min    -17.332816   -5.687363  -7.480823   -2.782244  -8.489499  -17.576979   
25%     -4.723309   -0.012234   1.937311   -0.030832  -2.529257   -6.181715   
50%      1.766188    1.203539   4.844067    0.876726  -0.304095   -2.343305   
75%      6.979031    3.173161   7.101202    1.768763   1.521719    2.538118   
max     25.453964    6.511094  13.786866    4.707807   5.659826   20.618052   

               6  
count  63.000000  
mean   -0.773534  
std    31.587754  
min   -67.652579  
25%   -26.291974  
50%    -0.094008  
75%    20.978511  
max    85.144253

In [23]:
data = data.to_numpy()

In [29]:
mean = np.nanmean(data,axis=0)
mean

array([ 1.82449455,  1.34428927,  4.42848274,  0.8071502 , -0.78784003,
       -1.94448293, -0.7735345 ])

In [30]:
std = np.nanstd(data,axis=0)
std

array([ 8.57330098,  2.3674376 ,  4.32008121,  1.41239345,  3.08261496,
        6.60406082, 31.33605474])

In [31]:
def norm(data):
    mean = np.nanmean(data,axis=0)
    std = np.nanstd(data,axis=0)
    
    return (data-mean)/std
    

In [32]:
norm(data)

array([[-1.0719495 , -1.49749709, -0.83380329,  0.70665422,         nan,
         0.07400326,         nan],
       [-0.423068  ,  0.50526993,         nan, -1.54287662,  0.43700532,
        -0.64679425,         nan],
       [-0.76895699, -0.5326035 ,  0.58561779, -0.13365055,  0.8658342 ,
        -0.33044038, -0.91826972],
       [-0.18856038,  1.39965829,  0.19281096, -0.50574631, -1.95768708,
         0.62153926, -0.01527993],
       [ 0.38311415,  0.96005515, -0.85831676,  2.76173519,  1.0957639 ,
         1.03374399,  1.47371237],
       [ 0.58482285, -0.28705881,  0.37000834,  0.82382254, -0.15738367,
        -0.99464135,  0.36681086],
       [ 0.16851898, -0.06024145,  0.20569404, -1.02754011,         nan,
        -0.99200314,         nan],
       [-0.22518145, -1.26375648,         nan, -0.12831185, -0.10344194,
         0.28310215,         nan],
       [-0.4492785 ,  1.61244607,  1.97186482,  1.4285881 ,         nan,
        -0.20572639,         nan],
       [-1.8133362 , -1.2270