# Clase 3
## Ejercicio 1

In [1]:
import numpy as np
import pandas as pd
rng = np.random.default_rng(seed=18)

In [3]:
data = pd.read_csv("../data/clase3V2.csv",delimiter=';',header=None)
data

0         1          2         3         4          5          6
0    3.669506  2.863605        NaN  2.948632       NaN  -9.364512   7.564543
1   13.505001  4.482330        NaN  0.770769       NaN  -3.706287  32.866898
2   -5.736774 -1.030994        NaN  0.907981       NaN   5.332656 -20.922094
3   -0.019325  1.909841        NaN  0.137427       NaN   3.400036   1.433380
4    6.079670  1.528345        NaN  0.746475       NaN -11.486688  11.867943
..        ...       ...        ...       ...       ...        ...        ...
95   0.029921  5.364063   9.676388  2.644617  1.877694  -7.677102  24.897925
96  -1.775782  5.393318   3.854789  3.186040 -1.403002  -3.622327  18.237007
97  13.162143  0.164868  12.263580  3.105625 -0.426276  -1.829889  43.654064
98   7.060369  4.293074   3.590226 -0.066123 -2.039099  -3.643987  18.831133
99 -23.815965  3.424658   1.601140  1.270134 -2.037267   6.164295 -69.318103

[100 rows x 7 columns]

In [4]:
#referencia de resultados con pandas
data.describe()

0           1          2           3          4           5  \
count  100.000000  100.000000  75.000000  100.000000  85.000000  100.000000   
mean     2.271986    1.284816   4.184569    1.103956  -0.631169   -3.834794   
std      7.751563    2.740007   4.660731    1.438916   3.032243    7.069103   
min    -23.815965   -5.059008  -8.072152   -3.508639  -7.623845  -20.539008   
25%     -2.345455   -0.840319   1.624254    0.268422  -2.168176   -8.456255   
50%      2.408766    1.176410   4.246226    0.968645  -0.510668   -3.675137   
75%      6.985025    3.177441   7.683205    1.992865   1.342859    0.003910   
max     19.922689    8.867793  14.018366    4.873960   6.575618   13.681640   

                6  
count  100.000000  
mean     1.509312  
std     28.973492  
min    -84.198849  
25%    -16.327087  
50%      0.999340  
75%     21.401164  
max     73.444107

In [5]:
data = data.to_numpy()

In [6]:
mean = np.nanmean(data,axis=0)
mean

array([ 2.27198551,  1.28481564,  4.18456924,  1.10395579, -0.63116864,
       -3.83479401,  1.5093118 ])

In [7]:
std = np.nanstd(data,axis=0)
std

array([ 7.7127077 ,  2.72627245,  4.6295548 ,  1.43170342,  3.01435321,
        7.03366832, 28.82826044])

In [8]:
def norm(data):
    mean = np.nanmean(data,axis=0)
    std = np.nanstd(data,axis=0)
    
    return (data-mean)/std
    

In [9]:
norm(data)

array([[ 1.81197104e-01,  5.79101757e-01,             nan,
         1.28844866e+00,             nan, -7.86178421e-01,
         2.10044985e-01],
       [ 1.45642962e+00,  1.17285218e+00,             nan,
        -2.32720546e-01,             nan,  1.82703320e-02,
         1.08773771e+00],
       [-1.03838489e+00, -8.49441749e-01,             nan,
        -1.36882551e-01,             nan,  1.30336678e+00,
        -7.78104726e-01],
       [-2.97082527e-01,  2.29259874e-01,             nan,
        -6.75090072e-01,             nan,  1.02859985e+00,
        -2.63394190e-03],
       [ 4.93689757e-01,  8.93267068e-02,             nan,
        -2.49688912e-01,             nan, -1.08789524e+00,
         3.59322101e-01],
       [-1.14557027e+00, -2.96345673e-01,             nan,
        -1.17396924e+00,             nan, -1.66141057e-01,
        -1.36751796e+00],
       [-1.21693648e+00,  6.89171947e-01,             nan,
        -1.89585116e-01,             nan, -3.79005340e-01,
        -8.7589156